// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: AggregateArticleService.proto

package aggregate_article_service_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *String                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOneRequest) Reset() {
	*x = ReadOneRequest{}
	mi := &file_AggregateArticleService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOneRequest) ProtoMessage() {}

func (x *ReadOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AggregateArticleService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOneRequest.ProtoReflect.Descriptor instead.
func (*ReadOneRequest) Descriptor() ([]byte, []int) {
	return file_AggregateArticleService_proto_rawDescGZIP(), []int{0}
}

func (x *ReadOneRequest) GetId() *String {
	if x != nil {
		return x.Id
	}
	return nil
}

type ReadOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Body          *ReadOneResponseBody   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOneResponse) Reset() {
	*x = ReadOneResponse{}
	mi := &file_AggregateArticleService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOneResponse) ProtoMessage() {}

func (x *ReadOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AggregateArticleService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOneResponse.ProtoReflect.Descriptor instead.
func (*ReadOneResponse) Descriptor() ([]byte, []int) {
	return file_AggregateArticleService_proto_rawDescGZIP(), []int{1}
}

func (x *ReadOneResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReadOneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReadOneResponse) GetBody() *ReadOneResponseBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type ReadOneResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       string                 `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"` //Serialized
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOneResponseBody) Reset() {
	*x = ReadOneResponseBody{}
	mi := &file_AggregateArticleService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOneResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOneResponseBody) ProtoMessage() {}

func (x *ReadOneResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_AggregateArticleService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOneResponseBody.ProtoReflect.Descriptor instead.
func (*ReadOneResponseBody) Descriptor() ([]byte, []int) {
	return file_AggregateArticleService_proto_rawDescGZIP(), []int{2}
}

func (x *ReadOneResponseBody) GetArticle() string {
	if x != nil {
		return x.Article
	}
	return ""
}

type ReadAllPaginatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNumber    *Int32                 `protobuf:"bytes,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	CountPerPage  *Int32                 `protobuf:"bytes,2,opt,name=count_per_page,json=countPerPage,proto3" json:"count_per_page,omitempty"`
	UserId        *String                `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SearchText    *String                `protobuf:"bytes,4,opt,name=search_text,json=searchText,proto3" json:"search_text,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllPaginatedRequest) Reset() {
	*x = ReadAllPaginatedRequest{}
	mi := &file_AggregateArticleService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllPaginatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllPaginatedRequest) ProtoMessage() {}

func (x *ReadAllPaginatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AggregateArticleService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllPaginatedRequest.ProtoReflect.Descriptor instead.
func (*ReadAllPaginatedRequest) Descriptor() ([]byte, []int) {
	return file_AggregateArticleService_proto_rawDescGZIP(), []int{3}
}

func (x *ReadAllPaginatedRequest) GetPageNumber() *Int32 {
	if x != nil {
		return x.PageNumber
	}
	return nil
}

func (x *ReadAllPaginatedRequest) GetCountPerPage() *Int32 {
	if x != nil {
		return x.CountPerPage
	}
	return nil
}

func (x *ReadAllPaginatedRequest) GetUserId() *String {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *ReadAllPaginatedRequest) GetSearchText() *String {
	if x != nil {
		return x.SearchText
	}
	return nil
}

func (x *ReadAllPaginatedRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ReadAllPaginatedResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Code          int32                         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Body          *ReadAllPaginatedResponseBody `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllPaginatedResponse) Reset() {
	*x = ReadAllPaginatedResponse{}
	mi := &file_AggregateArticleService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllPaginatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllPaginatedResponse) ProtoMessage() {}

func (x *ReadAllPaginatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AggregateArticleService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllPaginatedResponse.ProtoReflect.Descriptor instead.
func (*ReadAllPaginatedResponse) Descriptor() ([]byte, []int) {
	return file_AggregateArticleService_proto_rawDescGZIP(), []int{4}
}

func (x *ReadAllPaginatedResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReadAllPaginatedResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReadAllPaginatedResponse) GetBody() *ReadAllPaginatedResponseBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type ReadAllPaginatedResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      string                 `protobuf:"bytes,1,opt,name=articles,proto3" json:"articles,omitempty"` //Serialized
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAllPaginatedResponseBody) Reset() {
	*x = ReadAllPaginatedResponseBody{}
	mi := &file_AggregateArticleService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAllPaginatedResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAllPaginatedResponseBody) ProtoMessage() {}

func (x *ReadAllPaginatedResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_AggregateArticleService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAllPaginatedResponseBody.ProtoReflect.Descriptor instead.
func (*ReadAllPaginatedResponseBody) Descriptor() ([]byte, []int) {
	return file_AggregateArticleService_proto_rawDescGZIP(), []int{5}
}

func (x *ReadAllPaginatedResponseBody) GetArticles() string {
	if x != nil {
		return x.Articles
	}
	return ""
}

type String struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *String) Reset() {
	*x = String{}
	mi := &file_AggregateArticleService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_AggregateArticleService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_AggregateArticleService_proto_rawDescGZIP(), []int{6}
}

func (x *String) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Int32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32) Reset() {
	*x = Int32{}
	mi := &file_AggregateArticleService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32) ProtoMessage() {}

func (x *Int32) ProtoReflect() protoreflect.Message {
	mi := &file_AggregateArticleService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32.ProtoReflect.Descriptor instead.
func (*Int32) Descriptor() ([]byte, []int) {
	return file_AggregateArticleService_proto_rawDescGZIP(), []int{7}
}

func (x *Int32) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_AggregateArticleService_proto protoreflect.FileDescriptor

const file_AggregateArticleService_proto_rawDesc = "" +
	"\n" +
	"\x1dAggregateArticleService.proto\x12 Domic.Core.AggregateArticle.Grpc\"J\n" +
	"\x0eReadOneRequest\x128\n" +
	"\x02id\x18\x01 \x01(\v2(.Domic.Core.AggregateArticle.Grpc.StringR\x02id\"\x8a\x01\n" +
	"\x0fReadOneResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12I\n" +
	"\x04body\x18\x03 \x01(\v25.Domic.Core.AggregateArticle.Grpc.ReadOneResponseBodyR\x04body\"/\n" +
	"\x13ReadOneResponseBody\x12\x18\n" +
	"\aarticle\x18\x01 \x01(\tR\aarticle\"\xdd\x02\n" +
	"\x17ReadAllPaginatedRequest\x12H\n" +
	"\vpage_number\x18\x01 \x01(\v2'.Domic.Core.AggregateArticle.Grpc.Int32R\n" +
	"pageNumber\x12M\n" +
	"\x0ecount_per_page\x18\x02 \x01(\v2'.Domic.Core.AggregateArticle.Grpc.Int32R\fcountPerPage\x12A\n" +
	"\auser_id\x18\x03 \x01(\v2(.Domic.Core.AggregateArticle.Grpc.StringR\x06userId\x12I\n" +
	"\vsearch_text\x18\x04 \x01(\v2(.Domic.Core.AggregateArticle.Grpc.StringR\n" +
	"searchText\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\"\x9c\x01\n" +
	"\x18ReadAllPaginatedResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12R\n" +
	"\x04body\x18\x03 \x01(\v2>.Domic.Core.AggregateArticle.Grpc.ReadAllPaginatedResponseBodyR\x04body\":\n" +
	"\x1cReadAllPaginatedResponseBody\x12\x1a\n" +
	"\barticles\x18\x01 \x01(\tR\barticles\"\x1e\n" +
	"\x06String\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1d\n" +
	"\x05Int32\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value2\x99\x02\n" +
	"\x17AggregateArticleService\x12p\n" +
	"\aReadOne\x120.Domic.Core.AggregateArticle.Grpc.ReadOneRequest\x1a1.Domic.Core.AggregateArticle.Grpc.ReadOneResponse\"\x00\x12\x8b\x01\n" +
	"\x10ReadAllPaginated\x129.Domic.Core.AggregateArticle.Grpc.ReadAllPaginatedRequest\x1a:.Domic.Core.AggregateArticle.Grpc.ReadAllPaginatedResponse\"\x00BZZXgithub.com/HasanProgrammer/aggregate_article_service_grpc;aggregate_article_service_grpcb\x06proto3"

var (
	file_AggregateArticleService_proto_rawDescOnce sync.Once
	file_AggregateArticleService_proto_rawDescData []byte
)

func file_AggregateArticleService_proto_rawDescGZIP() []byte {
	file_AggregateArticleService_proto_rawDescOnce.Do(func() {
		file_AggregateArticleService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AggregateArticleService_proto_rawDesc), len(file_AggregateArticleService_proto_rawDesc)))
	})
	return file_AggregateArticleService_proto_rawDescData
}

var file_AggregateArticleService_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_AggregateArticleService_proto_goTypes = []any{
	(*ReadOneRequest)(nil),               // 0: Domic.Core.AggregateArticle.Grpc.ReadOneRequest
	(*ReadOneResponse)(nil),              // 1: Domic.Core.AggregateArticle.Grpc.ReadOneResponse
	(*ReadOneResponseBody)(nil),          // 2: Domic.Core.AggregateArticle.Grpc.ReadOneResponseBody
	(*ReadAllPaginatedRequest)(nil),      // 3: Domic.Core.AggregateArticle.Grpc.ReadAllPaginatedRequest
	(*ReadAllPaginatedResponse)(nil),     // 4: Domic.Core.AggregateArticle.Grpc.ReadAllPaginatedResponse
	(*ReadAllPaginatedResponseBody)(nil), // 5: Domic.Core.AggregateArticle.Grpc.ReadAllPaginatedResponseBody
	(*String)(nil),                       // 6: Domic.Core.AggregateArticle.Grpc.String
	(*Int32)(nil),                        // 7: Domic.Core.AggregateArticle.Grpc.Int32
}
var file_AggregateArticleService_proto_depIdxs = []int32{
	6, // 0: Domic.Core.AggregateArticle.Grpc.ReadOneRequest.id:type_name -> Domic.Core.AggregateArticle.Grpc.String
	2, // 1: Domic.Core.AggregateArticle.Grpc.ReadOneResponse.body:type_name -> Domic.Core.AggregateArticle.Grpc.ReadOneResponseBody
	7, // 2: Domic.Core.AggregateArticle.Grpc.ReadAllPaginatedRequest.page_number:type_name -> Domic.Core.AggregateArticle.Grpc.Int32
	7, // 3: Domic.Core.AggregateArticle.Grpc.ReadAllPaginatedRequest.count_per_page:type_name -> Domic.Core.AggregateArticle.Grpc.Int32
	6, // 4: Domic.Core.AggregateArticle.Grpc.ReadAllPaginatedRequest.user_id:type_name -> Domic.Core.AggregateArticle.Grpc.String
	6, // 5: Domic.Core.AggregateArticle.Grpc.ReadAllPaginatedRequest.search_text:type_name -> Domic.Core.AggregateArticle.Grpc.String
	5, // 6: Domic.Core.AggregateArticle.Grpc.ReadAllPaginatedResponse.body:type_name -> Domic.Core.AggregateArticle.Grpc.ReadAllPaginatedResponseBody
	0, // 7: Domic.Core.AggregateArticle.Grpc.AggregateArticleService.ReadOne:input_type -> Domic.Core.AggregateArticle.Grpc.ReadOneRequest
	3, // 8: Domic.Core.AggregateArticle.Grpc.AggregateArticleService.ReadAllPaginated:input_type -> Domic.Core.AggregateArticle.Grpc.ReadAllPaginatedRequest
	1, // 9: Domic.Core.AggregateArticle.Grpc.AggregateArticleService.ReadOne:output_type -> Domic.Core.AggregateArticle.Grpc.ReadOneResponse
	4, // 10: Domic.Core.AggregateArticle.Grpc.AggregateArticleService.ReadAllPaginated:output_type -> Domic.Core.AggregateArticle.Grpc.ReadAllPaginatedResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_AggregateArticleService_proto_init() }
func file_AggregateArticleService_proto_init() {
	if File_AggregateArticleService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AggregateArticleService_proto_rawDesc), len(file_AggregateArticleService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AggregateArticleService_proto_goTypes,
		DependencyIndexes: file_AggregateArticleService_proto_depIdxs,
		MessageInfos:      file_AggregateArticleService_proto_msgTypes,
	}.Build()
	File_AggregateArticleService_proto = out.File
	file_AggregateArticleService_proto_goTypes = nil
	file_AggregateArticleService_proto_depIdxs = nil
}
