// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: AggregateArticleService.proto

package aggregate_article_service_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AggregateArticleService_ReadOne_FullMethodName          = "/Domic.Core.AggregateArticle.Grpc.AggregateArticleService/ReadOne"
	AggregateArticleService_ReadAllPaginated_FullMethodName = "/Domic.Core.AggregateArticle.Grpc.AggregateArticleService/ReadAllPaginated"
)

// AggregateArticleServiceClient is the client API for AggregateArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AggregateArticleServiceClient interface {
	ReadOne(ctx context.Context, in *ReadOneRequest, opts ...grpc.CallOption) (*ReadOneResponse, error)
	ReadAllPaginated(ctx context.Context, in *ReadAllPaginatedRequest, opts ...grpc.CallOption) (*ReadAllPaginatedResponse, error)
}

type aggregateArticleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregateArticleServiceClient(cc grpc.ClientConnInterface) AggregateArticleServiceClient {
	return &aggregateArticleServiceClient{cc}
}

func (c *aggregateArticleServiceClient) ReadOne(ctx context.Context, in *ReadOneRequest, opts ...grpc.CallOption) (*ReadOneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadOneResponse)
	err := c.cc.Invoke(ctx, AggregateArticleService_ReadOne_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregateArticleServiceClient) ReadAllPaginated(ctx context.Context, in *ReadAllPaginatedRequest, opts ...grpc.CallOption) (*ReadAllPaginatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAllPaginatedResponse)
	err := c.cc.Invoke(ctx, AggregateArticleService_ReadAllPaginated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregateArticleServiceServer is the server API for AggregateArticleService service.
// All implementations must embed UnimplementedAggregateArticleServiceServer
// for forward compatibility.
type AggregateArticleServiceServer interface {
	ReadOne(context.Context, *ReadOneRequest) (*ReadOneResponse, error)
	ReadAllPaginated(context.Context, *ReadAllPaginatedRequest) (*ReadAllPaginatedResponse, error)
	mustEmbedUnimplementedAggregateArticleServiceServer()
}

// UnimplementedAggregateArticleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAggregateArticleServiceServer struct{}

func (UnimplementedAggregateArticleServiceServer) ReadOne(context.Context, *ReadOneRequest) (*ReadOneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadOne not implemented")
}
func (UnimplementedAggregateArticleServiceServer) ReadAllPaginated(context.Context, *ReadAllPaginatedRequest) (*ReadAllPaginatedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAllPaginated not implemented")
}
func (UnimplementedAggregateArticleServiceServer) mustEmbedUnimplementedAggregateArticleServiceServer() {
}
func (UnimplementedAggregateArticleServiceServer) testEmbeddedByValue() {}

// UnsafeAggregateArticleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggregateArticleServiceServer will
// result in compilation errors.
type UnsafeAggregateArticleServiceServer interface {
	mustEmbedUnimplementedAggregateArticleServiceServer()
}

func RegisterAggregateArticleServiceServer(s grpc.ServiceRegistrar, srv AggregateArticleServiceServer) {
	// If the following call panics, it indicates UnimplementedAggregateArticleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AggregateArticleService_ServiceDesc, srv)
}

func _AggregateArticleService_ReadOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateArticleServiceServer).ReadOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregateArticleService_ReadOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateArticleServiceServer).ReadOne(ctx, req.(*ReadOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggregateArticleService_ReadAllPaginated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllPaginatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregateArticleServiceServer).ReadAllPaginated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregateArticleService_ReadAllPaginated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregateArticleServiceServer).ReadAllPaginated(ctx, req.(*ReadAllPaginatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AggregateArticleService_ServiceDesc is the grpc.ServiceDesc for AggregateArticleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AggregateArticleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Domic.Core.AggregateArticle.Grpc.AggregateArticleService",
	HandlerType: (*AggregateArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadOne",
			Handler:    _AggregateArticleService_ReadOne_Handler,
		},
		{
			MethodName: "ReadAllPaginated",
			Handler:    _AggregateArticleService_ReadAllPaginated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "AggregateArticleService.proto",
}
